spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/dev}

spring.freemarker.suffix=.ftl

server.port=${PORT:3000}

minio.host=${MINIO_HOST:localhost}
minio.port=${MINIO_PORT:9000}
minio.bucket=${MINIO_BUCKET:image-storage}
minio.access-key=${MINIO_ACCESS_KEY:}
minio.secret-key=${MINIO_SECRET_KEY:}
minio.reconnect-enabled=${MINIO_RECONNECT_ENABLED:true}
